version: '3'
services:

  spring-boot:
    build: ./mvp
    ports:
      - "8080:8080"
    depends_on:
      - redis
  
  redis:
    image: redis:7.2
    container_name: mvp_redis_db
    ports:
      - "6379:6379"
