version: '3'
services:
  angular:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app 
      - /app/node_modules 
    depends_on:
      - spring-boot
    environment:
      - BACKEND_URL=http://spring-boot:8080

  spring-boot:
    build: ./mvp
    ports:
      - "8080:8080"
    depends_on:
      - redis
  
  redis:
    image: redis:7.2
    container_name: mvp_redis_db
    ports:
      - "6379:6379"
